// menuItems.js
export const menuItems = [
	{
		id: 1,
		name: "Salade César",
		price: 6,
		description: "Salade avec poulet, croûtons et sauce César.",
		vegan: false,
		glutenFree: false,
	},
	{
		id: 2,
		name: "Soupe de légumes",
		price: 5,
		description: "Soupe maison de légumes frais.",
		vegan: true,
		glutenFree: true,
	},
	{
		id: 3,
		name: "Pizza Margherita",
		price: 12,
		description: "Tomate, mozzarella, basilic.",
		vegan: false,
		glutenFree: false,
	},
	{
		id: 4,
		name: "Pâtes Carbonara",
		price: 14,
		description: "Pâtes avec lardons et crème.",
		vegan: false,
		glutenFree: false,
	},
	{
		id: 5,
		name: "Curry de légumes",
		price: 13,
		description: "Légumes et lait de coco.",
		vegan: true,
		glutenFree: true,
	},
	{
		id: 6,
		name: "Tiramisu",
		price: 6,
		description: "Dessert italien classique.",
		vegan: false,
		glutenFree: false,
	},
	{
		id: 7,
		name: "Coca-Cola",
		price: 2,
		description: "Boisson gazeuse classique.",
		vegan: true,
		glutenFree: true,
	},
	{
		id: 8,
		name: "Bière blonde",
		price: 4,
		description: "Bière pression.",
		vegan: true,
		glutenFree: false,
	},
];
