import { StyleSheet, Dimensions } from "react-native";
import { PREMIUM_COLORS } from "../theme/colors";

const SCREEN_WIDTH = Dimensions.get("window").width;

const appStyles = StyleSheet.create({
	container: {
		flex: 1,
		padding: 20,
		paddingTop: 50,
		backgroundColor: "#fff",
	},
	listContainer: {
		padding: 15,
		paddingBottom: 200,
	},
	productCard: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		backgroundColor: "#fff",
		padding: 15,
		borderRadius: 12,
		marginBottom: 10,
		elevation: 2,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.05,
		shadowRadius: 3,
	},
	productInfo: {
		flex: 1,
		marginRight: 15,
	},
	productName: {
		fontSize: 16,
		fontWeight: "600",
		color: "#333",
		marginBottom: 5,
	},
	productDescription: {
		fontSize: 14,
		color: "#666",
		marginBottom: 5,
	},
	productTags: {
		flexDirection: "row",
		flexWrap: "wrap",
		marginTop: 5,
	},
	tag: {
		fontSize: 11,
		paddingHorizontal: 8,
		paddingVertical: 3,
		borderRadius: 12,
		marginRight: 5,
		marginTop: 3,
	},
	veganTag: {
		backgroundColor: "#E8F5E9",
		color: "#2E7D32",
	},
	glutenTag: {
		backgroundColor: "#FFF3E0",
		color: "#EF6C00",
	},
	allergens: {
		fontSize: 12,
		color: "#ff6b6b",
		fontStyle: "italic",
		marginTop: 3,
	},
	price: {
		fontSize: 18,
		fontWeight: "bold",
		color: "#4CAF50",
		marginBottom: 8,
	},
	productInfo: {
		flex: 1,
		marginRight: 15,
	},
	productName: {
		fontSize: 16,
		fontWeight: "600",
		color: "#333",
		marginBottom: 5,
	},
	productDescription: {
		fontSize: 14,
		color: "#666",
		marginBottom: 5,
	},
	price: {
		fontSize: 18,
		fontWeight: "bold",
		color: "#4CAF50",
	},
	floatingCart: {
		position: "absolute",
		bottom: 20,
		left: 20,
		right: 20,
		backgroundColor: "#fff",
		borderRadius: 15,
		padding: 15,
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		elevation: 8,
	},
	modalOverlay: {
		flex: 1,
		backgroundColor: "rgba(0,0,0,0.5)",
		justifyContent: "center",
		alignItems: "center",
	},
	modalContent: {
		width: "85%",
		backgroundColor: "#fff",
		borderRadius: 15,
		padding: 20,
		alignItems: "center",
	},
	modalTitle: {
		fontSize: 20,
		fontWeight: "700",
		color: "#333",
		marginBottom: 8,
	},
	modalDescription: {
		fontSize: 14,
		color: "#555",
		textAlign: "center",
		lineHeight: 20,
	},
	center: { justifyContent: "center", alignItems: "center" },

	counterButton: {
		height: 32,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#ddd",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "#f8f9fa",
	},
	counterText: {
		fontSize: 18,
		fontWeight: "700",
		color: "#333",
	},
	counterValue: {
		marginHorizontal: 10,
		fontSize: 16,
		fontWeight: "500",
		color: "#333",
	},
	floatingCart: {
		position: "absolute",
		bottom: 20,
		left: 20,
		right: 20,
		backgroundColor: "#fff",
		borderRadius: 15,
		padding: 15,
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		elevation: 8,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.15,
		shadowRadius: 8,
	},
	floatingCartInfo: {
		flex: 1,
	},
	floatingCartCount: {
		fontSize: 14,
		fontWeight: "600",
		color: "#333",
	},
	floatingCartTotal: {
		fontSize: 18,
		fontWeight: "bold",
		color: "#4CAF50",
	},
	floatingCartButton: {
		backgroundColor: "#4CAF50",
		paddingHorizontal: 20,
		paddingVertical: 12,
		borderRadius: 10,
	},
	floatingCartButtonText: {
		color: "#fff",
		fontWeight: "bold",
		fontSize: 14,
	},
	searchContainer: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#fff",
		borderRadius: 12,
		paddingHorizontal: 12,
		marginBottom: 15,
		elevation: 3,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
	},
	searchInput: {
		flex: 1,
		paddingVertical: 12,
		fontSize: 15,
		color: "#333",
	},
	emptyState: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		paddingVertical: 50,
	},
	emptyStateText: {
		fontSize: 16,
		color: "#999",
	},
	modalOverlay: {
		flex: 1,
		backgroundColor: "rgba(0,0,0,0.5)",
		justifyContent: "center",
		alignItems: "center",
	},
	modalContent: {
		width: "85%",
		backgroundColor: "#fff",
		borderRadius: 15,
		padding: 20,
		alignItems: "center",
	},
	modalTitle: {
		fontSize: 20,
		fontWeight: "700",
		color: "#333",
		marginBottom: 8,
	},
	modalDescription: {
		fontSize: 14,
		color: "#555",
		textAlign: "center",
		lineHeight: 20,
	},
	premiumHeader: {
		marginBottom: 16,
		paddingTop: 8,
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},

	headerIconContainer: {
		position: "relative",
		width: 56,
		height: 56,
		justifyContent: "center",
		alignItems: "center",
		marginRight: 8,
	},
	headerIcon: {
		width: 56,
		height: 56,
		borderRadius: 14,
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 6 },
		shadowOpacity: 0.12,
		shadowRadius: 12,
		elevation: 8,
	},
	allergyBadgeAbsolute: {
		position: "absolute",
		top: -6,
		right: -6,
		width: 20,
		height: 20,
		borderRadius: 10,
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 2,
		borderColor: "#fff",
	},
	allergyBadgeText: {
		fontSize: 12,
		fontWeight: "800",
		color: "#fff",
	},
	premiumSearchContainer: {
		marginBottom: 12,
		borderRadius: 12,
		borderWidth: 1,
		overflow: "hidden",
	},
	premiumProductName: {
		fontSize: 18,
		fontWeight: "700",
		color: PREMIUM_COLORS?.text || "#111",
	},
	payButtonGradient: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		paddingVertical: 12,
		borderRadius: 12,
	},
	center: {
		justifyContent: "center",
		alignItems: "center",
	},
	emptySearchSubtext: {
		fontSize: 14,
		color: "#999",
	},
	categoriesBar: {
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		gap: 8,
		marginBottom: 20,
		paddingHorizontal: 5,
	},
	animatedButton: {
		borderRadius: 30,
		justifyContent: "center",
		alignItems: "center",
		overflow: "hidden",
		backgroundColor: "#fff",
		elevation: 5,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 3 },
		shadowOpacity: 0.15,
		shadowRadius: 5,
	},
	glowEffect: {
		position: "absolute",
		top: 10,
		left: 0,
		right: 0,
		bottom: 0,
		borderRadius: 30,
		opacity: 0,
		transform: [{ scale: 1.1 }],
	},
	buttonEmoji: {
		fontSize: 24,
		position: "absolute",
	},
	buttonText: {
		color: "#fff",
		fontSize: 12,
		fontWeight: "700",
		letterSpacing: 1.5,
		textTransform: "uppercase",
		position: "absolute",
	},
	categoryPillWrapper: {
		flex: 1,
		marginHorizontal: 4,
	},
	categoryPillGradient: {
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		paddingVertical: 14,
		paddingHorizontal: 8,
		borderRadius: 16,
		elevation: 6,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: 6,
	},
	categoryPillInactive: {
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		paddingVertical: 14,
		paddingHorizontal: 8,
		borderRadius: 16,
		backgroundColor: "#fff",
		elevation: 3,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
	},
	categoryEmoji: {
		fontSize: 24,
		marginBottom: 4,
	},
	categoryPillText: {
		fontSize: 11,
		fontWeight: "700",
		textAlign: "center",
		textTransform: "uppercase",
		letterSpacing: 0.5,
	},
	noCategorySelected: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		paddingHorizontal: 30,
		paddingBottom: 100,
	},
	noCategoryText: {
		fontSize: 20,
		fontWeight: "700",
		color: "#1a1a2e",
		marginBottom: 8,
		textAlign: "center",
	},
	noCategorySubtext: {
		fontSize: 14,
		color: "#666",
		textAlign: "center",
	},
	emptyCategory: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		paddingVertical: 50,
	},
	emptyCategoryText: {
		fontSize: 16,
		color: "#999",
	},
	payButtonFloat: {
		position: "absolute",
		bottom: 20,
		left: 20,
		right: 20,
		backgroundColor: "#2196F3",
		padding: 15,
		borderRadius: 12,
		alignItems: "center",
	},
	payButtonText: {
		color: "#fff",
		fontWeight: "bold",
		fontSize: 16,
	},
	categoriesGrid: {
		flexDirection: "row",
		flexWrap: "wrap",
		justifyContent: "space-between",
	},
	categoryCard: {
		width: "48%",
		height: 150,
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
		marginBottom: 15,
		elevation: 5,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 3 },
		shadowOpacity: 0.1,
		shadowRadius: 5,
	},
	categoryIcon: {
		marginBottom: 10,
	},
	categoryTitle: {
		fontSize: 18,
		fontWeight: "bold",
		color: "#fff",
		textAlign: "center",
	},
	productActions: {
		alignItems: "center",
	},
	cartContainer: {
		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
		backgroundColor: "#fff",
		padding: 15,
		borderTopWidth: 1,
		borderColor: "#eee",
		elevation: 10,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: -2 },
		shadowOpacity: 0.1,
		shadowRadius: 5,
	},
	cartTitle: {
		fontWeight: "bold",
		fontSize: 16,
		marginBottom: 10,
		color: "#333",
	},
	emptyCart: {
		fontStyle: "italic",
		color: "#999",
		textAlign: "center",
		padding: 10,
	},
	cartItems: {
		flexDirection: "row",
	},
	cartItem: {
		backgroundColor: "#f0f0f0",
		paddingHorizontal: 12,
		paddingVertical: 6,
		borderRadius: 16,
		marginRight: 8,
		flexDirection: "row",
		alignItems: "center",
	},
	cartItemName: {
		fontSize: 14,
		color: "#333",
	},
	cartItemQty: {
		fontSize: 14,
		fontWeight: "bold",
		color: "#4CAF50",
		marginLeft: 4,
	},
	quickCart: {
		backgroundColor: "#fff",
		borderRadius: 15,
		padding: 15,
		marginTop: 20,
		elevation: 3,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
	},
	quickCartTitle: {
		fontWeight: "bold",
		fontSize: 16,
		marginBottom: 10,
		color: "#333",
	},
	quickCartItems: {
		flexDirection: "row",
		marginBottom: 10,
	},
	quickCartItem: {
		backgroundColor: "#f0f0f0",
		paddingHorizontal: 10,
		paddingVertical: 5,
		borderRadius: 12,
		marginRight: 8,
		flexDirection: "row",
		alignItems: "center",
	},
	quickCartName: {
		fontSize: 13,
		color: "#333",
	},
	quickCartQty: {
		fontSize: 13,
		fontWeight: "bold",
		color: "#4CAF50",
		marginLeft: 3,
	},
	quickCartButton: {
		backgroundColor: "#4CAF50",
		paddingVertical: 12,
		borderRadius: 10,
		alignItems: "center",
	},
	quickCartButtonText: {
		color: "#fff",
		fontWeight: "bold",
		fontSize: 16,
	},
	mainButtonsContainer: {
		marginTop: 30,
		marginBottom: 20,
		gap: 15,
	},
	mainActionButton: {
		paddingVertical: 18,
		borderRadius: 12,
		alignItems: "center",
		justifyContent: "center",
		elevation: 3,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.2,
		shadowRadius: 3,
	},
	mainValidateButton: {
		backgroundColor: "#4CAF50",
	},
	mainViewOrderButton: {
		backgroundColor: "#2196F3",
	},
	mainPayButton: {
		backgroundColor: "#FF9800",
	},
	mainActionButtonText: {
		color: "#fff",
		fontWeight: "bold",
		fontSize: 18,
	},
	buttonsContainer: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginTop: 15,
		gap: 10,
	},
	actionButton: {
		flex: 1,
		paddingVertical: 15,
		borderRadius: 10,
		alignItems: "center",
		justifyContent: "center",
	},
	validateButton: {
		backgroundColor: "#4CAF50",
	},
	payButton: {
		backgroundColor: "#FF9800",
	},
	actionButtonText: {
		color: "#fff",
		fontWeight: "bold",
		fontSize: 16,
	},
	modalOverlayDark: {
		flex: 1,
		backgroundColor: "rgba(0,0,0,0.8)",
		justifyContent: "center",
		alignItems: "center",
	},
	modalImage: {
		width: "100%",
		height: 200,
		borderRadius: 12,
		marginVertical: 15,
		backgroundColor: "#f0f0f0",
	},
	modalTags: {
		flexDirection: "row",
		marginBottom: 15,
	},
	modalTag: {
		fontSize: 12,
		paddingHorizontal: 10,
		paddingVertical: 4,
		borderRadius: 12,
		marginHorizontal: 5,
	},
	modalVeganTag: {
		backgroundColor: "#E8F5E9",
		color: "#2E7D32",
	},
	modalGlutenTag: {
		backgroundColor: "#FFF3E0",
		color: "#EF6C00",
	},
	modalAllergens: {
		fontSize: 14,
		fontStyle: "italic",
		marginBottom: 20,
		textAlign: "center",
	},
	infoPriceContainer: {
		alignSelf: "center",
		backgroundColor: "#667eea",
		paddingHorizontal: 20,
		paddingVertical: 8,
		borderRadius: 20,
		marginVertical: 10,
	},
	infoPriceText: {
		color: "#fff",
		fontSize: 20,
		fontWeight: "700",
	},
	infoOptionsOneLine: {
		fontSize: 15,
		color: "#555",
		textAlign: "center",
		marginTop: 15,
		fontStyle: "italic",
	},
	infoOptionsContainer: {
		marginTop: 15,
		paddingTop: 15,
		borderTopWidth: 1,
		borderTopColor: "#e0e0e0",
	},
	infoOptionsTitle: {
		fontSize: 15,
		fontWeight: "600",
		color: "#333",
		marginBottom: 10,
	},
	infoOptionItem: {
		flexDirection: "row",
		justifyContent: "space-between",
		paddingVertical: 8,
		paddingHorizontal: 10,
		backgroundColor: "#f9f9f9",
		borderRadius: 8,
		marginBottom: 6,
	},
	infoOptionName: {
		fontSize: 14,
		color: "#555",
	},
	infoOptionPrice: {
		fontSize: 14,
		fontWeight: "600",
		color: "#667eea",
	},
	infoAllergensContainer: {
		marginTop: 15,
		paddingTop: 15,
		borderTopWidth: 1,
		borderTopColor: "#e0e0e0",
	},
	modalCloseButton: {
		backgroundColor: "#4CAF50",
		paddingVertical: 12,
		paddingHorizontal: 40,
		borderRadius: 10,
	},
	modalCloseText: {
		color: "#fff",
		fontWeight: "bold",
		fontSize: 16,
	},
	optionsContainer: {
		width: "100%",
		marginTop: 20,
		marginBottom: 15,
	},
	optionsTitle: {
		fontSize: 16,
		fontWeight: "700",
		color: "#333",
		marginBottom: 12,
	},
	optionItem: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		paddingVertical: 12,
		paddingHorizontal: 15,
		borderRadius: 10,
		backgroundColor: "#f5f5f5",
		marginBottom: 8,
		borderWidth: 2,
		borderColor: "transparent",
	},
	optionItemSelected: {
		backgroundColor: "#E8F5E9",
		borderColor: "#4CAF50",
	},
	optionLeft: {
		flexDirection: "row",
		alignItems: "center",
		flex: 1,
	},
	optionCheckbox: {
		fontSize: 20,
		marginRight: 10,
	},
	optionRadio: {
		fontSize: 20,
		marginRight: 10,
	},
	optionName: {
		fontSize: 15,
		fontWeight: "500",
		color: "#333",
		flex: 1,
	},
	optionPrice: {
		fontSize: 14,
		fontWeight: "600",
		color: "#4CAF50",
	},
	optionsLoading: {
		paddingVertical: 20,
	},
	optionsLoadingText: {
		fontSize: 14,
		color: "#999",
		textAlign: "center",
	},
	modalButtons: {
		flexDirection: "row",
		marginTop: 10,
		gap: 10,
		width: "100%",
	},
	modalCancelButton: {
		backgroundColor: "#9E9E9E",
	},
	modalAddButton: {
		backgroundColor: "#4CAF50",
	},
	modalCancelText: {
		color: "#fff",
		fontWeight: "bold",
		fontSize: 16,
	},
	modalAddText: {
		color: "#fff",
		fontWeight: "bold",
		fontSize: 16,
	},
	premiumListContainer: {
		paddingHorizontal: 5,
		paddingBottom: 150,
	},
	premiumCard: {
		borderRadius: 20,
		marginBottom: 16,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.15,
		shadowRadius: 12,
		elevation: 6,
		borderWidth: 1,
		borderColor: "rgba(255,255,255,0.08)",
	},
	cardAccentLine: {
		height: 4,
		width: "100%",
		borderTopLeftRadius: 20,
		borderTopRightRadius: 20,
		overflow: "hidden",
	},
	premiumCardContent: {
		flexDirection: "row",
		padding: 18,
		justifyContent: "space-between",
		backgroundColor: "rgba(255,255,255,0.07)",
		borderBottomLeftRadius: 20,
		borderBottomRightRadius: 20,
	},
	premiumCardInfo: {
		flex: 1,
		paddingRight: 12,
	},
	premiumProductDesc: {
		fontSize: 14,
		color: PREMIUM_COLORS.textMuted,
		lineHeight: 18,
		marginBottom: 10,
	},
	premiumTagsRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 6,
	},
	premiumTag: {
		backgroundColor: "rgba(76,175,80,0.12)",
		paddingHorizontal: 8,
		paddingVertical: 4,
		borderRadius: 8,
	},
	premiumTagText: {
		fontSize: 11,
		fontWeight: "600",
		color: PREMIUM_COLORS.text,
	},
	premiumCardActions: {
		alignItems: "flex-end",
		justifyContent: "space-between",
	},
	premiumPriceBadge: {
		paddingHorizontal: 14,
		paddingVertical: 8,
		borderRadius: 12,
		marginBottom: 12,
		shadowColor: "#764ba2",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.18,
		shadowRadius: 6,
		elevation: 4,
	},
	premiumPriceText: {
		fontSize: 16,
		fontWeight: "800",
		color: PREMIUM_COLORS.text,
	},
	premiumCounter: {
		flexDirection: "row",
		alignItems: "center",
		gap: 4,
	},
	premiumCounterBtn: {
		borderRadius: 12,
		overflow: "hidden",
	},
	premiumCounterGradient: {
		width: 36,
		height: 36,
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 12,
	},
	premiumCounterText: {
		fontSize: 20,
		fontWeight: "700",
		color: "#fff",
	},
	premiumCounterValueContainer: {
		width: 32,
		alignItems: "center",
	},
	premiumCounterValue: {
		fontSize: 16,
		fontWeight: "700",
		color: PREMIUM_COLORS.textMuted,
	},
	premiumCounterValueActive: {
		color: PREMIUM_COLORS.text,
	},
	noCategoryGradient: {
		padding: 40,
		borderRadius: 24,
		alignItems: "center",
	},
	noCategoryEmoji: {
		fontSize: 60,
		marginBottom: 16,
	},
	premiumFloatingCart: {
		position: "absolute",
		bottom: 20,
		left: 16,
		right: 16,
		borderRadius: 20,
		overflow: "hidden",
	},
	premiumCartBlur: {
		borderRadius: 20,
		overflow: "hidden",
	},
	premiumCartGradient: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingVertical: 12,
		paddingHorizontal: 16,
		borderRadius: 20,
		borderWidth: 1,
		borderColor: "rgba(0,0,0,0.05)",
	},
	premiumCartInfo: {
		flexDirection: "row",
		alignItems: "center",
	},
	premiumCartBadge: {
		backgroundColor: "#667eea",
		width: 32,
		height: 32,
		borderRadius: 16,
		justifyContent: "center",
		alignItems: "center",
		marginRight: 12,
	},
	premiumCartBadgeText: {
		color: "#fff",
		fontWeight: "800",
		fontSize: 14,
	},
	premiumCartTextContainer: {},
	premiumCartLabel: {
		fontSize: 12,
		color: "#666",
		fontWeight: "500",
	},
	premiumCartTotal: {
		fontSize: 18,
		fontWeight: "800",
		color: "#1a1a2e",
	},
	premiumCartButton: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 20,
		paddingVertical: 12,
		borderRadius: 14,
		gap: 8,
	},
	premiumCartButtonText: {
		color: "#fff",
		fontWeight: "700",
		fontSize: 14,
	},
	searchResultsCount: {
		fontSize: 14,
		color: "#666",
		marginBottom: 10,
		fontWeight: "500",
	},
	searchResultHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		marginBottom: 4,
	},
	categoryBadge: {
		paddingHorizontal: 8,
		paddingVertical: 3,
		borderRadius: 10,
	},
	categoryBadgeText: {
		fontSize: 10,
		color: "#fff",
		fontWeight: "600",
	},
	emptySearch: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		paddingVertical: 50,
	},
	emptySearchEmoji: {
		fontSize: 50,
		marginBottom: 15,
	},
	emptySearchText: {
		fontSize: 16,
		color: "#333",
		fontWeight: "500",
		marginBottom: 5,
	},
	welcomeTitle: {
		fontSize: 32,
		fontWeight: "800",
		letterSpacing: -0.5,
		textAlign: "center",
	},
	subtitle: {
		fontSize: 16,
		fontWeight: "500",
		textAlign: "center",
		marginTop: 4,
	},
	premiumSearchGradient: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 16,
		paddingVertical: 4,
	},
	premiumSearchInput: {
		flex: 1,
		paddingVertical: 14,
		fontSize: 16,
		color: PREMIUM_COLORS.text,
		fontWeight: "500",
	},
	searchIcon: {
		marginRight: 12,
	},
	clearButton: {
		padding: 4,
	},
	clearButtonInner: {
		backgroundColor: "#667eea",
		borderRadius: 12,
		padding: 4,
	},
});

export default appStyles;
