import { StyleSheet, Dimensions } from "react-native";
import { GRILLZ_THEME } from "../theme/colors";

const SCREEN_WIDTH = Dimensions.get("window").width;

// Styles spécifiques pour Grillz (foodtruck) - Thème orange/rouge/noir BBQ
const appStyles = StyleSheet.create({
	container: {
		flex: 1,
		padding: 20,
		paddingTop: 50,
		backgroundColor: "#181818",
	},
	// Décorations Grillz
	bgDecor: {
		...StyleSheet.absoluteFillObject,
		overflow: "hidden",
	},
	bgCircle: {
		position: "absolute",
		borderRadius: 999,
		opacity: 0.25,
	},
	bgCircle1: {
		width: SCREEN_WIDTH * 0.7,
		height: SCREEN_WIDTH * 0.7,
		top: -SCREEN_WIDTH * 0.2,
		right: -SCREEN_WIDTH * 0.2,
	},
	bgCircle2: {
		width: SCREEN_WIDTH * 0.5,
		height: SCREEN_WIDTH * 0.5,
		bottom: 100,
		left: -SCREEN_WIDTH * 0.2,
	},
	// Header Grillz
	premiumHeader: {
		marginBottom: 20,
		alignItems: "center",
		paddingTop: 10,
	},
	headerIconContainer: {
		position: "relative",
		width: 70,
		height: 70,
		justifyContent: "center",
		alignItems: "center",
		marginBottom: 16,
	},
	headerIcon: {
		width: 70,
		height: 70,
		borderRadius: 35,
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#ff512f",
		shadowOffset: { width: 0, height: 8 },
		shadowOpacity: 0.6,
		shadowRadius: 16,
		elevation: 12,
	},
	allergyBadgeAbsolute: {
		position: "absolute",
		top: -6,
		right: -6,
		width: 24,
		height: 24,
		borderRadius: 12,
		backgroundColor: "#ff9800",
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 2,
		borderColor: "#181818",
	},
	allergyBadgeText: {
		fontSize: 12,
		fontWeight: "800",
		color: "#181818",
	},
	welcomeTitle: {
		fontSize: 32,
		fontWeight: "800",
		color: "#fff",
		letterSpacing: -0.5,
		textAlign: "center",
		textShadowColor: "#ff512f",
		textShadowRadius: 12,
		textShadowOffset: { width: 0, height: 2 },
	},
	subtitle: {
		fontSize: 16,
		color: "#ff9800",
		fontWeight: "700",
		textAlign: "center",
		marginTop: 4,
		textShadowColor: "#fff",
		textShadowRadius: 8,
	},
	// Barre de recherche Grillz
	premiumSearchContainer: {
		marginBottom: 20,
		borderRadius: 16,
		borderWidth: 2,
		borderColor: "#ff512f",
		overflow: "hidden",
		backgroundColor: "rgba(24, 24, 24, 0.8)",
	},
	premiumSearchGradient: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 16,
		paddingVertical: 4,
	},
	premiumSearchInput: {
		flex: 1,
		paddingVertical: 14,
		fontSize: 16,
		color: "#fff",
		fontWeight: "500",
	},
	searchIcon: {
		marginRight: 12,
	},
	clearButton: {
		padding: 4,
	},
	clearButtonInner: {
		backgroundColor: "#ff512f",
		borderRadius: 12,
		padding: 4,
	},
	// Résultats de recherche
	searchResultsCount: {
		fontSize: 14,
		color: "#ff9800",
		marginBottom: 10,
		fontWeight: "700",
	},
	emptySearch: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		paddingVertical: 50,
	},
	emptySearchEmoji: {
		fontSize: 50,
		marginBottom: 15,
	},
	emptySearchText: {
		fontSize: 16,
		color: "#fff",
		fontWeight: "700",
		marginBottom: 5,
		textShadowColor: "#ff512f",
		textShadowRadius: 8,
	},
	emptySearchSubtext: {
		fontSize: 14,
		color: "#ff9800",
	},
	// Barre de catégories
	categoriesBar: {
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		gap: 8,
		marginBottom: 20,
		paddingHorizontal: 5,
	},
	animatedButton: {
		borderRadius: 30,
		justifyContent: "center",
		alignItems: "center",
		overflow: "hidden",
		backgroundColor: "#181818",
		elevation: 8,
		shadowColor: "#ff512f",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.4,
		shadowRadius: 8,
	},
	glowEffect: {
		position: "absolute",
		top: 10,
		left: 0,
		right: 0,
		bottom: 0,
		borderRadius: 30,
		opacity: 0,
		transform: [{ scale: 1.1 }],
	},
	buttonEmoji: {
		fontSize: 24,
		position: "absolute",
	},
	buttonText: {
		color: "#fff",
		fontSize: 12,
		fontWeight: "700",
		letterSpacing: 1.5,
		textTransform: "uppercase",
		position: "absolute",
	},
	// État vide
	noCategorySelected: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		paddingHorizontal: 30,
		paddingBottom: 100,
	},
	noCategoryGradient: {
		padding: 40,
		borderRadius: 24,
		alignItems: "center",
	},
	noCategoryEmoji: {
		fontSize: 60,
		marginBottom: 16,
		textShadowColor: "#ff9800",
		textShadowRadius: 16,
		textShadowOffset: { width: 0, height: 4 },
	},
	noCategoryText: {
		fontSize: 32,
		fontWeight: "900",
		color: "#fff",
		marginBottom: 8,
		textAlign: "center",
		textShadowColor: "#ff512f",
		textShadowRadius: 12,
		textShadowOffset: { width: 0, height: 2 },
	},
	noCategorySubtext: {
		fontSize: 18,
		color: "#ff9800",
		fontWeight: "bold",
		textAlign: "center",
		textShadowColor: "#fff",
		textShadowRadius: 8,
	},
	emptyCategory: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		paddingVertical: 50,
	},
	emptyCategoryText: {
		fontSize: 16,
		color: "#ff9800",
	},
	// Liste premium
	premiumListContainer: {
		paddingHorizontal: 5,
		paddingBottom: 150,
	},
	// Carte produit Grillz
	premiumCard: {
		borderRadius: 20,
		marginBottom: 16,
		shadowColor: "#ff512f",
		shadowOffset: { width: 0, height: 6 },
		shadowOpacity: 0.4,
		shadowRadius: 16,
		elevation: 10,
		borderWidth: 2,
		borderColor: "rgba(255, 81, 47, 0.3)",
		backgroundColor: "rgba(24, 24, 24, 0.9)",
	},
	cardAccentLine: {
		height: 4,
		width: "100%",
		borderTopLeftRadius: 20,
		borderTopRightRadius: 20,
		overflow: "hidden",
	},
	premiumCardContent: {
		flexDirection: "row",
		padding: 18,
		justifyContent: "space-between",
		backgroundColor: "rgba(24, 24, 24, 0.95)",
		borderBottomLeftRadius: 20,
		borderBottomRightRadius: 20,
	},
	premiumCardInfo: {
		flex: 1,
		paddingRight: 12,
	},
	premiumProductName: {
		fontSize: 18,
		fontWeight: "700",
		color: "#fff",
		marginBottom: 6,
		letterSpacing: -0.3,
		textShadowColor: "#ff512f",
		textShadowRadius: 4,
		textShadowOffset: { width: 0, height: 1 },
	},
	premiumProductDesc: {
		fontSize: 14,
		color: "#ff9800",
		lineHeight: 18,
		marginBottom: 10,
	},
	premiumTagsRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 6,
	},
	premiumTag: {
		backgroundColor: "rgba(255, 152, 0, 0.2)",
		paddingHorizontal: 8,
		paddingVertical: 4,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#ff9800",
	},
	premiumTagText: {
		fontSize: 11,
		fontWeight: "600",
		color: "#ff9800",
	},
	premiumCardActions: {
		alignItems: "flex-end",
		justifyContent: "space-between",
	},
	premiumPriceBadge: {
		paddingHorizontal: 14,
		paddingVertical: 8,
		borderRadius: 12,
		marginBottom: 12,
		shadowColor: "#ff9800",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.6,
		shadowRadius: 8,
		elevation: 6,
	},
	premiumPriceText: {
		fontSize: 16,
		fontWeight: "800",
		color: "#fff",
	},
	premiumCounter: {
		flexDirection: "row",
		alignItems: "center",
		gap: 4,
	},
	premiumCounterBtn: {
		borderRadius: 12,
		overflow: "hidden",
	},
	premiumCounterGradient: {
		width: 36,
		height: 36,
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 12,
	},
	premiumCounterText: {
		fontSize: 20,
		fontWeight: "700",
		color: "#fff",
	},
	premiumCounterValueContainer: {
		width: 32,
		alignItems: "center",
	},
	premiumCounterValue: {
		fontSize: 16,
		fontWeight: "700",
		color: "#ff9800",
	},
	premiumCounterValueActive: {
		color: "#fff",
		textShadowColor: "#ff512f",
		textShadowRadius: 4,
		textShadowOffset: { width: 0, height: 1 },
	},
	// Panier flottant Grillz
	premiumFloatingCart: {
		position: "absolute",
		bottom: 20,
		left: 16,
		right: 16,
		borderRadius: 20,
		overflow: "hidden",
		shadowColor: "#ff512f",
		shadowOffset: { width: 0, height: 8 },
		shadowOpacity: 0.6,
		shadowRadius: 20,
		elevation: 15,
	},
	premiumCartBlur: {
		borderRadius: 20,
		overflow: "hidden",
	},
	premiumCartGradient: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingVertical: 12,
		paddingHorizontal: 16,
		borderRadius: 20,
		borderWidth: 2,
		borderColor: "#ff512f",
	},
	premiumCartInfo: {
		flexDirection: "row",
		alignItems: "center",
	},
	premiumCartBadge: {
		backgroundColor: "#ff9800",
		width: 32,
		height: 32,
		borderRadius: 16,
		justifyContent: "center",
		alignItems: "center",
		marginRight: 12,
	},
	premiumCartBadgeText: {
		color: "#181818",
		fontWeight: "800",
		fontSize: 14,
	},
	premiumCartTextContainer: {},
	premiumCartLabel: {
		fontSize: 12,
		color: "#ff9800",
		fontWeight: "700",
	},
	premiumCartTotal: {
		fontSize: 18,
		fontWeight: "800",
		color: "#fff",
		textShadowColor: "#ff512f",
		textShadowRadius: 4,
		textShadowOffset: { width: 0, height: 1 },
	},
	premiumCartButton: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 20,
		paddingVertical: 12,
		borderRadius: 14,
		gap: 8,
	},
	premiumCartButtonText: {
		color: "#fff",
		fontWeight: "700",
		fontSize: 14,
	},
	// Bouton paiement
	payButtonFloat: {
		position: "absolute",
		bottom: 20,
		left: 20,
		right: 20,
		borderRadius: 12,
		overflow: "hidden",
		shadowColor: "#ff512f",
		shadowOffset: { width: 0, height: 8 },
		shadowOpacity: 0.6,
		shadowRadius: 16,
		elevation: 12,
	},
	payButtonGradient: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		paddingVertical: 12,
		borderRadius: 12,
	},
	payButtonText: {
		color: "#fff",
		fontWeight: "bold",
		fontSize: 16,
		textShadowColor: "#000",
		textShadowRadius: 2,
		textShadowOffset: { width: 0, height: 1 },
	},
	// Modal
	modalOverlayDark: {
		flex: 1,
		backgroundColor: "rgba(0,0,0,0.95)",
		justifyContent: "center",
		alignItems: "center",
	},
	modalContent: {
		width: "85%",
		backgroundColor: "#181818",
		borderRadius: 15,
		padding: 20,
		alignItems: "center",
		borderWidth: 2,
		borderColor: "#ff512f",
	},
	modalTitle: {
		fontSize: 20,
		fontWeight: "700",
		color: "#fff",
		marginBottom: 8,
		textShadowColor: "#ff512f",
		textShadowRadius: 4,
		textShadowOffset: { width: 0, height: 1 },
	},
	modalImage: {
		width: "100%",
		height: 200,
		borderRadius: 12,
		marginVertical: 15,
		backgroundColor: "#000",
		borderWidth: 1,
		borderColor: "#ff512f",
	},
	modalAllergens: {
		fontSize: 14,
		fontStyle: "italic",
		marginBottom: 20,
		textAlign: "center",
		color: "#ff9800",
	},
	infoPriceContainer: {
		alignSelf: "center",
		backgroundColor: "#ff512f",
		paddingHorizontal: 20,
		paddingVertical: 8,
		borderRadius: 20,
		marginVertical: 10,
	},
	infoPriceText: {
		color: "#fff",
		fontSize: 20,
		fontWeight: "700",
	},
	infoOptionsOneLine: {
		fontSize: 15,
		color: "#ff9800",
		textAlign: "center",
		marginTop: 15,
		fontStyle: "italic",
	},
	infoAllergensContainer: {
		marginTop: 15,
		paddingTop: 15,
		borderTopWidth: 1,
		borderTopColor: "#ff512f",
	},
	modalCloseButton: {
		backgroundColor: "#ff9800",
		paddingVertical: 12,
		paddingHorizontal: 40,
		borderRadius: 10,
	},
	modalCloseText: {
		color: "#181818",
		fontWeight: "bold",
		fontSize: 16,
	},
	// Options produit
	optionsContainer: {
		width: "100%",
		marginTop: 20,
		marginBottom: 15,
	},
	optionsTitle: {
		fontSize: 16,
		fontWeight: "700",
		color: "#fff",
		marginBottom: 12,
	},
	optionItem: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		paddingVertical: 12,
		paddingHorizontal: 15,
		borderRadius: 10,
		backgroundColor: "rgba(24, 24, 24, 0.8)",
		marginBottom: 8,
		borderWidth: 2,
		borderColor: "transparent",
	},
	optionItemSelected: {
		backgroundColor: "rgba(255, 81, 47, 0.2)",
		borderColor: "#ff512f",
	},
	optionLeft: {
		flexDirection: "row",
		alignItems: "center",
		flex: 1,
	},
	optionRadio: {
		fontSize: 20,
		marginRight: 10,
	},
	optionName: {
		fontSize: 15,
		fontWeight: "500",
		color: "#fff",
		flex: 1,
	},
	optionPrice: {
		fontSize: 14,
		fontWeight: "600",
		color: "#ff9800",
	},
	optionsLoading: {
		paddingVertical: 20,
	},
	optionsLoadingText: {
		fontSize: 14,
		color: "#ff9800",
		textAlign: "center",
	},
	modalButtons: {
		flexDirection: "row",
		marginTop: 10,
		gap: 10,
		width: "100%",
	},
	modalButton: {
		flex: 1,
		paddingVertical: 15,
		borderRadius: 10,
		alignItems: "center",
		justifyContent: "center",
	},
	modalCancelButton: {
		backgroundColor: "#666",
	},
	modalAddButton: {
		backgroundColor: "#ff9800",
	},
	modalCancelText: {
		color: "#fff",
		fontWeight: "bold",
		fontSize: 16,
	},
	modalAddText: {
		color: "#181818",
		fontWeight: "bold",
		fontSize: 16,
	},
	center: {
		justifyContent: "center",
		alignItems: "center",
	},
});

export default appStyles;
